export default function Loading() {
    return(
        <>
            <title>Pedro Grimaldi Hansel</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            
        </>
    )
}