import Head from 'next/head'
import type { NextPage } from 'next'
//import Navbar from '../components/NavBar'
import styles from '../styles/scss/index.module.scss'
import Image from "next/image";
import foto from '../public/images/FotoPedro.jpeg'
import NavbarMobile from '@/components/NavBarMobile';



export default function Home() {
  return (
    <>
      <Head>
        <title>Pedro Grimaldi Hansel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarMobile/>
      <main className={styles.Home}>
       
       <section className={styles.Home_top}>
        <div className={styles.foto_de_perfil}>
          <a href="https://github.com/Pedro-Grimaldi-Hansel" target="_blank" rel="noreferrer"><Image alt='Foto de perfil' src={foto}/></a>
        </div>
       </section>

       <section className={styles.Home_text}>
        <h1>Pedro Grimaldi</h1>
        <p> Sou estudante de graduação em Ciencias Exatas e Ciencias da Computação (UFJF) e trabalho atualmete como desenvolvedor, gerente de projetos e conselheiro multiplicador na Code Empresa Jr de computação.</p>
       </section>

       <section className={styles.GitHubStats}>
        <a href="https://github.com/Pedro-Grimaldi-Hansel" target="_blank" rel="noreferrer">
        <img src="https://github-readme-stats.vercel.app/api/top-langs/?username=Pedro-Grimaldi-Hansel&count_private=true&layout=compact&bg_color=374A67&text_color=ffffff&title_color=ffffff&hide_border=true&border_radius=25"/>
        </a>
       </section>
      </main>
    </>
  )
}
